urls.py
from django.urls import path
from . import views

app_name = 'ifsearch'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.search, name='query'),
]

models.py
from django.db import models

# Create your models here.


class If(models.Model):
    journal = models.CharField(max_length=200, blank=False)
    iff = models.FloatField()
    year = models.CharField(max_length=4, blank=False)

    def __str__(self):
        return '-'.join([self.journal, self.year])

views.py
from django.shortcuts import render
from .models import If
from .iform import SearchForm
# Create your views here.


def search(request):
    if request.method == 'GET':
        journal = request.GET['journal']
        # journal = str(journal).lower()
        if journal == '':
            return render(request, 'ifsearch/index.html')
        year = str(request.GET['year'])
        year = ['2017','2016'] if year=='All' else [year]
        querys = If.objects.filter(journal__iexact=journal, year__in=year)
        # if something goes wrong, no info returned, do blur search
        if len(querys)==0:
            core_words = journal.split()
            core_string = [x for x in core_words if x != 'the' and x != 'of']
            querys = If.objects.filter(journal__icontains=' '.join(core_string),year__in=year).order_by('-iff')
            context = {
                'info': '{0} is not found, check the similar below'.format(journal.upper()),
                'ifs': querys,
                'journal': journal.upper(),}
            return render(request, 'ifsearch/result.html', context=context)
        # else: everything is OK, do below
        context = {
            'info': 'success',
            'ifs': querys,
            'journal': journal.upper(),}
        return render(request, 'ifsearch/result.html', context=context)

def index(request):
    return render(request, 'ifsearch/index.html')

templates/ifsearch/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}  {% endblock %} </title>
</head>
<body>
{% block content %} {% endblock %}

</body>
</html>

templates/ifsearch/index.html
{% extends "ifsearch/base.html" %}
{% block title %} Home Page {% endblock %}
{% load static %}
{% block content %}
<div id="container" style="display: flex; margin-top:20%; justify-content: center;align-items: center;vertical-align:middle">
    <form action="{% url 'ifsearch:query' %}" method="get">
        <input type="text" name="journal" style="display:inline-block; width: 400px; vertical-align:top; height: 50px; color: green; font-size: 30px;
        line-height: 50px; box-sizing: border-box; -webkit-box-sizing:border-box; -moz-box-sizing: border-box;
">
        <select name="year" style="height: 50px; width: 100px; display: inline-block; font-size: 30px">
            <option value="2017">2017</option>
            <option value="2016">2016</option>
            <option value="All">All Year</option>
        </select>
        <input type="submit" value="Search" style="height: 50px;display: inline-block; width: 150px; font-size: 30px">
    </form>
</div>
{% endblock %}

templates/ifsearch/result.html
{% extends "ifsearch/base.html" %}
{% block title %} Result {% endblock %}
{% load static %}
{% block content %}




<div id="container" style="width: 500px;margin-left: auto;margin-right: auto; border: 2px solid green;">
    <div id="back" style=" width: 500px;margin-left: 0px;margin-bottom: 20px;">
         <button onclick="window.location.href = '{% url "ifsearch:index" %}'"
            style="border: 2px solid green; border-bottom: 4px solid green; width: 500px;height: 50px; line-height: 50px; font-size: 30px;">Back</button>
    </div>
    <div id="inner" style="margin-left: 50px; margin-right: 50px">
    {% if info == 'success' %}
    <div><label>IF for Journal:</label><div style="margin-left: 10px;color: red;">{{ journal }}</div></div>
    {% else %}
    <div style="color: red;">{{ info }}</div>
    {% endif %}
    {%  for i in ifs %}
        <div style="margin-top: 20px;">{{ i.journal }}</div>
        <div><span style="margin-left: 15px;">{{ i.year }}:</span><span style="color:red;margin-left: 10px;">{{ i.iff }}</span></div>

    {% endfor %}
    </div>

</div>
{% endblock %}